version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          # remove this when Appium drops Node 10 support
          dependency_name: "extract-zip"
